### ISSUE TITLE
bonus du TP HTTPS sur mi-lxc

### ISSUE THREAD

**Issue by JeanRibes** [flesueur/csc#5]
j'ai eu quelques problèmes avec les commandes à la fin du TP:

pour le côté serveur, il fallait rajouter ``SSLClientVerify require`` pour que le serveur refuse le client

pour la partie génération du certificat, la commande `step-ca certificate` ne marchait pas, on peut utiliser la commande `step  certificate create "IspAhome" client.crt client.key --ca .step/certs/root_ca.crt --ca-key .step/secrets/root_ca_key`

**Comment by flesueur** [comment]
Merci, tu as super bien compris l'intérêt d'avoir les sujets sur github :innocent: 

Pour le SSLClientVerify require -> ça a été mis à jour tout à l'heure pendant le TP (oui, nous aussi on débugge en prod, évidemment). Peux-tu me faire un retour sur cette version ?

Pour la commande step ça m'étonne de devoir mettre tout ça... Par contre en effet il faut que step-ca tourne (comme pour ACME), j'ai l'impression que la "bonne" solution est entre le sujet et ta ligne, je vais regarder, merci !

**Comment by flesueur** [comment]
Est-ce que 483385b résout le step ca ?

**Comment by JeanRibes** [comment]
je n'avais pas vu pour la mise à jour du sujet

par contre j'avais effectivement lancé `step-ca` avant de créer les certificats

**Comment by JeanRibes** [comment]
> Est-ce que [483385b](https://github.com/flesueur/csc/commit/483385b71cf018cc53d2177c63e54bfb85bd2fc3) résout le step ca ?

la commande marche (j'ai sélectionné `JWKS`), mais après le serveur web refuse le client (`SSL_ERROR_INTERNAL_ERROR_ALERT`)

**Comment by flesueur** [comment]
Bizarre, ça a marché chez Nicolas... Je laisse ouvert et j'irai investiguer du coup, merci !

**Comment by flesueur** [comment]
Ça a marché avec un autre groupe, je pense qu'il y a eu dans ton cas une histoire d'état interne de la CA avec l'enchaînement des différents modes, ça semble ok maintenant. Merci !
